-- Fact-grounded AI personalization: per-lead generated opener + provenance.
-- Generated by the batch personalization tick, read at send time. Idempotent.
ALTER TABLE lead_signals ADD COLUMN IF NOT EXISTS personalized_opener TEXT;
ALTER TABLE lead_signals ADD COLUMN IF NOT EXISTS personalization_fact TEXT;
ALTER TABLE lead_signals ADD COLUMN IF NOT EXISTS personalization_model TEXT;
ALTER TABLE lead_signals ADD COLUMN IF NOT EXISTS personalization_at TIMESTAMPTZ;

-- Partial index for the tick: find leads still needing an opener.
CREATE INDEX IF NOT EXISTS ls_needs_opener ON lead_signals (org_id) WHERE personalized_opener IS NULL;
